// apps/web/src/lib/components/market/MarketStatusBar.tsx
import type { Market } from '@/lib/api/types';
import Badge from '@/lib/components/ui/Badge';
import { formatTokenAmount } from '@/lib/utils/amount';
import MarketPricePanel from './MarketPricePanel';

export default function MarketStatusBar({ market }: { market: Market }) {
  const total = market.outcomes.reduce((sum, outcome) => sum + BigInt(outcome.total_stake || '0'), 0n);
  const priceHeader = market.price_header;

  return (
    <section className="terminal-panel px-4 py-3">
      <div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between">
        <div className="flex min-w-0 items-center gap-4">
          {priceHeader ? (
            <img
              src={priceHeader.asset_image_url}
              alt={`${priceHeader.asset} market`}
              className="h-14 w-14 shrink-0 rounded-xl border border-terminal-line bg-terminal-bg"
            />
          ) : null}
          <div className="min-w-0">
            <p className="mono-label text-terminal-muted">market #{market.market_id}</p>
            <h1 className="mt-1 truncate text-xl font-black text-terminal-text sm:text-2xl">{market.question_hash}</h1>
            {priceHeader ? <p className="mt-2 text-xs font-semibold text-terminal-muted">{priceHeader.settlement_source}</p> : null}
          </div>
        </div>
        <div className="flex flex-col gap-3 lg:items-end">
          <MarketPricePanel priceHeader={priceHeader} showAssetImage={false} />
          <div className="flex flex-wrap items-center gap-2 lg:justify-end">
            <Badge tone={market.status === 'open' ? 'positive' : market.status === 'resolved' ? 'success' : 'neutral'}>{market.status}</Badge>
            <Badge tone="neutral">{market.outcome_count} outcomes</Badge>
            <Badge tone="neutral">{formatTokenAmount(total)} staked</Badge>
          </div>
        </div>
      </div>
    </section>
  );
}

// apps/web/src/lib/components/market/MarketStatusBar.svelte
<script lang="ts">
  import { Bookmark, Code2, Link2 } from 'lucide-svelte';
  import type { Market } from '$lib/api/types';
  import Badge from '$lib/components/ui/Badge.svelte';
  import Button from '$lib/components/ui/Button.svelte';

  let { market }: { market: Market } = $props();

  const closeLabel = $derived((() => {
    const diff = market.trade_until * 1000 - Date.now();
    if (diff <= 0) return 'Closed';
    const minutes = Math.ceil(diff / 60000);
    if (minutes < 60) return `${minutes}m left`;
    const hours = Math.ceil(minutes / 60);
    if (hours < 24) return `${hours}h left`;
    return `${Math.ceil(hours / 24)}d left`;
  })());
</script>

<section>
  <div class="flex items-start justify-between gap-3">
    <div class="flex min-w-0 items-start gap-3">
      <div class="grid h-12 w-12 shrink-0 place-items-center">
        <img src="/brand/bm-logo-mark.svg" alt="" aria-hidden="true" class="app-icon h-9 w-9" />
      </div>
      <div class="min-w-0">
        <h1 class="text-balance text-xl font-black leading-tight text-terminal-text sm:text-3xl">
          {market.question_hash}
        </h1>
        <div class="mt-1 flex flex-wrap items-center gap-2 text-sm font-bold text-terminal-muted sm:text-base">
          <span>{closeLabel}</span>
          <span>·</span>
          <Badge tone={market.status === 'open' ? 'positive' : 'neutral'}>{market.status}</Badge>
          <span>·</span>
          <span>{market.outcome_count} outcomes</span>
        </div>
      </div>
    </div>
    <div class="hidden shrink-0 items-center gap-2 text-terminal-text sm:flex">
      <Button class="h-8 w-8" size="icon" variant="ghost" aria-label="Embed"><Code2 size={16} /></Button>
      <Button class="h-8 w-8" size="icon" variant="ghost" aria-label="Copy link"><Link2 size={16} /></Button>
      <Button class="h-8 w-8" size="icon" variant="ghost" aria-label="Bookmark"><Bookmark size={16} /></Button>
    </div>
  </div>
</section>
